services:
  catalog:
    build: ./catalog-service
    ports:
      - "5001:5001"

  recommendation:
    build: ./recommendation-service
    ports:
      - "5000:5000"
    environment:
      - CATALOG_URL=http://catalog:5001
    depends_on:
      - catalog
